name: apptree_dart_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/apptreesoftware/apptree_dart_sdk

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  yaml_writer: ^2.1.0
  equatable: ^2.0.7
  langchain: ^0.7.7+2
  langchain_openai: ^0.7.3
  langchain_community: ^0.3.3
  langchain_core: ^0.3.6+1
  dotenv: ^4.2.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
