name: server
description: A package containing the apptree connector basic server template components
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  logging: ^1.2.0
  shelf_plus: ^1.10.0
  dotenv: ^4.2.0
  apptree_mobile:
    path: ../../../../apptree_7/dart_graph_sdk

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.12
  very_good_analysis: ^6.0.0
